[workspace]
members = ["crates/ic-query", "crates/ic-query-cli"]
resolver = "3"

[workspace.package]
version = "0.47.9"
edition = "2024"
rust-version = "1.91.0"
license = "MIT"
authors = ["borovan <84897664+borovan@users.noreply.github.com>"]
homepage = "https://github.com/dragginzgame/ic-query"
repository = "https://github.com/dragginzgame/ic-query"

[workspace.dependencies]
candid = { version = "0.10", default-features = false }
cap-fs-ext = "4.0.2"
cap-std = "4.0.2"
clap = { version = "4.6.1", features = ["derive"] }
futures = "0.3"
ic-agent = { version = "0.49.2", default-features = false }
ic-cdk = "0.20.2"
ic-host-artifacts = { version = "0.3.3", default-features = false }
ic-host-fs = { version = "0.3.3", default-features = false }
ic-host-tools = { version = "0.3.3", default-features = false }
ic-query = { path = "crates/ic-query", version = "0.47.9", default-features = false }
prost = "0.14.3"
reqwest = { version = "0.13.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0"
sha2 = "0.10.9"
thiserror = "2.0"
tokio = "1.52.3"
unicode-width = "0.2"
url = "2.5.8"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# always warn
missing_const_for_fn = "warn"
must_use_candidate = "warn"
redundant_clone = "warn"
semicolon_if_nothing_returned = "warn"
uninlined_format_args = "warn"
use_self = "warn"

# always allow
doc_markdown = "allow"
empty_line_after_doc_comments = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
needless_pass_by_value = "allow"
