[package]
name = "ic-query"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
description = "Internet Computer query library for NNS, SNS, ICRC, system canisters, and public network metadata"
readme = "../../README.md"
documentation = "https://docs.rs/ic-query"
homepage.workspace = true
repository.workspace = true
keywords = ["internet-computer", "dfinity", "icp", "nns", "sns"]
categories = ["command-line-utilities"]

[dependencies]
candid.workspace = true
futures = { version = "0.3", optional = true }
ic-agent = { version = "0.49.2", default-features = false, optional = true }
prost = { version = "0.14.3", optional = true }
reqwest = { version = "0.13.4", default-features = false, features = [
    "json",
    "rustls",
], optional = true }
serde.workspace = true
serde_cbor = { version = "0.11.2", optional = true }
serde_json.workspace = true
sha2 = { version = "0.10.9", optional = true }
thiserror.workspace = true
tokio = { version = "1.52.3", features = ["rt"], optional = true }
unicode-width = "0.2"
url = { version = "2.5.8", optional = true }

[features]
default = []
host = [
    "dep:futures",
    "dep:ic-agent",
    "dep:prost",
    "dep:reqwest",
    "dep:serde_cbor",
    "dep:sha2",
    "dep:tokio",
    "dep:url",
]

[[test]]
name = "ic_public_api"

[[test]]
name = "nns_public_api"

[[test]]
name = "sns_public_api"

[[test]]
name = "system_public_api"

[lints]
workspace = true
